/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hwuwqjcnzwpxquioxnuv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dXdxamNuendweHF1aW94bnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMDgwNzIsImV4cCI6MjA3OTc4NDA3Mn0.TrkRKJNtG-d198osbBgNWZnHttaZtdS_HfGOFz-vpgA"